packages:
  - "apps/*"
  - "packages/*"

catalog:
  dayjs: ^1.11.18
  typescript: ^5.9.2
  tailwindcss: ^4.1.11
  react: ^19.1.1
  react-dom: ^19.1.1
  '@types/node': ^24.9.1
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.2
  next: ^16.0.0
  next-themes: ^0.4.6
  tailwind-merge: ^3.3.1
  zod: ^4.1.12
  lucide-react: ^0.546.0
  clsx: ^2.1.1
  class-variance-authority: ^0.7.1
  '@radix-ui/react-slot': ^1.2.3
  '@tailwindcss/postcss': ^4.1.15